In [4]:
import requests  # [+] HTTP 요청
from bs4 import BeautifulSoup  # [+] 웹스크래핑
import pandas as pd

In [6]:
# 1. User-Agent 설정
# 우리가 실제 크롬 브라우저를 사용하는 일반 사용자인 것처럼 서버를 속이는 '위장 신분증' 역할
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}

search_keyword = '이란'  # [+] 검색 키워드
url = f'https://search.naver.com/search.naver?where=news&query={search_keyword}'  # 검색한 웹페이지 주소

In [99]:
# 2. 페이지 요청 및 파싱
res = requests.get(url, headers=headers)  # [+] 네이버 서버에 페이지 정보 요청(GET)
res.raise_for_status() # 서버가 응답을 잘 주었는지 확인(정상 200, 페이지 없음 404 등)
soup = BeautifulSoup(res.text, 'html.parser')  # [+] BeautifulSoup 객체 생성

In [205]:
# 3. 질문자님이 찾은 클래스로 타겟팅 (띄어쓰기를 '.'으로 변경)
# [+] 찾고자 하는 HTML 태그 정의
target_class = "span.sds-comps-text.sds-comps-text-ellipsis.sds-comps-text-ellipsis-2.sds-comps-text-type-headline1"
title_spans = soup.select(target_class) # [+] 조건에 맞는 모든 태그를 찾아 리스트로 저장

extracted_data = []

In [203]:
extracted_data=[]
for span in title_spans:
    text_data = span.text.strip()
    extracted_data.append(text_data)
print(extracted_data)

['[단독] 이란에 26척 정보 넘긴 韓구출작전…‘역봉쇄’ 변수 만났다', '미·이란, 물밑 대화 진행중…2차 대면협상 가능성도 준비', '"미국-이란 협상단, 이번주 후반 파키스탄서 만난다"', '미, 해상봉쇄 시작…트럼프 “이란, 간절히 합의 원해”', '정부, 이란에 한국 선박 정보 공유‥통항 협의 주목', '밴스 미 부통령 "1차 협상단은 권한 없었다⋯이제 공은 이란에"', '[속보] 미-이란 협상 기대감에 코스피, 장중 6000선 재돌파', '트럼프 명령한 이란 항구 봉쇄·기뢰 제거…"최고 난이도 임무"', '이란 대통령 "국제법 틀에서 협상, 성공 여부 美에 달려"', '미·이란 “대화 계속”…봉쇄 속에도 협상 불씨 살아있다']

In [187]:
# 파이썬이 가져온 전체 글자 덩어리 출력해보기
print(soup.text)

         이란 : 네이버 뉴스검색       메뉴 영역으로 바로가기 본문 영역으로 바로가기      NAVER   검색                   검색 검색    한글 입력기 입력도구      자동완성 레이어검색 레이어               전체뉴스블로그카페클립new이미지지식iN인플루언서동영상쇼핑숏텐츠어학사전지도도서지식백과학술정보   이전 다음     더보기   전체뉴스블로그카페클립new이미지지식iN인플루언서동영상쇼핑숏텐츠어학사전지도도서지식백과학술정보  검색옵션       공유      이란 뉴스검색 결과

















관련도순최신순모바일 메인 언론사옵션옵션정렬관련도순
최신순
오래된순서비스 영역전체
모바일 메인 언론사
PC 메인 언론사기간전체
1시간옵션펼치기접기
1일
1주
1개월
3개월
6개월
1년
직접입력옵션펼치기접기시간선택1시간2시간3시간4시간5시간6시간기간 설정시작
2026.04.14.

기간 설정끝
2026.04.14.년(Year)월(Month)일(Day)적용유형전체
포토
동영상
지면기사
보도자료
자동생성기사언론사전체
유형별옵션펼치기접기
언론사 분류순옵션펼치기접기
지역언론사별옵션펼치기접기
가나다순옵션펼치기접기유형선택일간지방송/통신경제/IT인터넷신문스포츠/연예지역지매거진전문지/기타언론사 분류선택언론사선택지역지 분류선택언론사선택가나다순 선택언론사선택기자명
삭제
적용옵션 초기화
옵션 유지
이 정보가 표시된 이유옵션을 유지할 경우 선택한 서비스 영역과 언론사로 필터링된 뉴스 결과가 계속 제공됩니다.정보확인 레이어 닫기서비스 영역과 언론사의 선택 옵션이 유지됩니다.옵션 가이드




언론사 선정언론사가 선정한 주요기사 혹은 심층기획 기사입니다. 네이버 메인에서 보고 싶은 언론사를 구독하세요.




중앙일보A5면 1단12시간 전네이버뉴스Keep에 저장Keep에 바로가기[단독] 이란에 26척 정보 넘긴 韓구출작전…‘역봉쇄’ 변수 만났다정부가 호르무즈 해협에 고립된 국적선 26척을 구출하기 위해 해당 선박들의 세부 정보를 이란 당국에 전달하면서 본격적 협상을 준비하는 것으로 13일 파악됐다. 2주간의 미·이란 휴전 종료(21일)가 8일 앞으로 다가온 가운데 정부는 중동 지역에 대한 추가 인도적 지원 규모 등도 이르면 이번주 중 확정할... 정부, 이란에 韓선박 정보 공유…통항 협의 주목(종합)연합뉴스6시간 전네이버뉴스정부, 이란 당국과 호르무즈 해협 韓선박 정보 공유뉴시스6시간 전네이버뉴스정부, 이란에 한국 선박 정보 공유…통항 협의 주목SBS5시간 전네이버뉴스정부, 이란 당국과 호르무즈 해협 韓선박 정보 공유…"유관국과 소통"(...뉴시스5시간 전네이버뉴스연합뉴스9시간 전네이버뉴스Keep에 저장Keep에 바로가기미·이란, 물밑 대화 진행중…2차 대면협상 가능성도 준비카드로 이란을 압박하고 있지만, 물밑에서는 여전히 타결 시도가 이어지고 있다는 보도가 나왔다. 13일(현지시간) 로이터 통신과 CNN 등 외신들은 미국 당국자와 협상 내용에 밝은 소식통을 인용해 미국과 이란 간 대화 카드가 여전히 살아있다고 보도했다. 한 미국 당국자는 "미국과 이란 사이에 지속적으로... 美-이란, 휴전 만료 전 2차 협상 움직임…밴스 "공은 이란에"뉴스18시간 전네이버뉴스"미·이란, 물밑 대화 진행 중"⋯두 번째 회담 논의MBN9시간 전네이버뉴스미·이란 긴장 최고조인데…"합의 진전 중" 물밑 협상 계속한국경제9시간 전네이버뉴스미·이란, 2차 협상 물밑 조율 중…대면협상 가능성도노컷뉴스7시간 전네이버뉴스관련뉴스 6건 전체보기TV조선49분 전네이버뉴스Keep에 저장Keep에 바로가기"미국-이란 협상단, 이번주 후반 파키스탄서 만난다"미국과 이란 협상단이 이번 주 후반 파키스탄 이슬라마바드에서 협상 테이블에 복귀할 예정이라는 외신 보도가 나왔다. 14일(현지시간) 로이터 통신은... 이같은 보도는 도널드 트럼프 미 대통령이 이란의 호르무즈 해협 봉쇄에 맞서 지난 13일 역봉쇄를 강행한 이후 나온 것이기도 하다.“미-이란 협상단, 이번주 이슬라마바드 복귀 가능성”KBS1시간 전네이버뉴스[속보] "미-이란 협상단, 이번 주 후반 파키스탄 복귀 예정"YTN51분 전네이버뉴스"미-이란 협상단, 이번주 후반 이슬라마바드 복귀 예정"연합뉴스51분 전네이버뉴스[속보] "美-이란 협상단, 이번주 후반 파키스탄 복귀 예정" [로이터]한국경제59분 전네이버뉴스관련뉴스 9건 전체보기KBS11시간 전네이버뉴스Keep에 저장Keep에 바로가기미, 해상봉쇄 시작…트럼프 “이란, 간절히 합의 원해”미국의 대이란 해상 봉쇄가 시작됐다고 트럼프 대통령이 직접 밝혔습니다. 트럼프는 그러면서 이란이 매우 간절히 합의를 원하고 있다면서 이란은 핵무기를 가져선 안 된다는 원칙을 거듭 강조했습니다. 워싱턴 김경수 특파원입니다. [리포트] 미국 동부 시각 13일 오전 10시, 우리 시각 어젯밤 11시부터 이란에... 트럼프, 호르무즈 봉쇄 공식 확인… “이란, 합의 간절히 원해”조선비즈14시간 전네이버뉴스트럼프 “대이란 해상봉쇄 개시… 이란, 협상 원한다 연락”조선비즈9시간 전네이버뉴스미, 해상봉쇄 시작…트럼프 “이란, 간절히 합의 원해”KBS5시간 전네이버뉴스MBC7시간 전네이버뉴스Keep에 저장Keep에 바로가기정부, 이란에 한국 선박 정보 공유‥통항 협의 주목정부가 이란과의 협의 과정에서 호르무즈 해협에 있는 한국 선박에 대한 정보를 공유한 것으로 전해졌습니다. 외교부에 따르면 이란을 방문한 정병하 외교장관 특사는 호르무즈 해협에 머물고 있는 한국 선박과 선원의 안전 문제 등을 협의하는 과정에서 선박 관련 정보를 공유한 것으로 알려졌습니다.... "정부, 호르무즈 발묶인 한국선박 26척 정보 이란에 공유"JTBC7시간 전네이버뉴스정부, 이란에 한국 선박 정보 전달…이란과의 양자 협의 및 국제사회 공...경향신문30분 전네이버뉴스정부, 이란에 韓선박 정보 공유…통항 협의 주목연합뉴스8시간 전네이버뉴스한국 선박 정보 이란에 제공...통항 협의 중YTN32분 전네이버뉴스관련뉴스 9건 전체보기MBN8시간 전네이버뉴스Keep에 저장Keep에 바로가기밴스 미 부통령 "1차 협상단은 권한 없었다⋯이제 공은 이란에"JD 밴스 미국 부통령은 이란과의 종전 협상에 대해 "향후 추가 대화가 이뤄질지, 궁극적으로 합의에 도달할지는 전적으로 이란 측에 달려있다"고 말했습니다. 밴스 부통령은 현지 시각 13일 폭스뉴스 인터뷰에서 "우리가 이미 (이란에) 많은 것을 제안했다"며 이같이 밝혔습니다. 그러면서 "이제 공은 이란 쪽에... 밴스 美부통령 "이제 공은 이란에…추가 대화도 이란에 달려"연합뉴스9시간 전네이버뉴스국민일보6시간 전네이버뉴스Keep에 저장Keep에 바로가기[속보] 미-이란 협상 기대감에 코스피, 장중 6000선 재돌파국내 증시의 맏형 코스피가 미국과 이란 간의 종전 협상 재개 기대감에 힘입어 장중 6000선을 다시 돌파했다. 14일 한국거래소에 따르면 이날 오전 10시12분 기준 코스피 지수는 전 거래일보다 191.56포인트(3.30%) 급등한 6000.18을 기록했다. 코스피 지수가 장중 6000선을 밟은 것은 미국과 이란 간 전쟁이 본격... [속보] 코스피, 미·이란 협상 기대감에 장중 6000선 재돌파중앙일보6시간 전네이버뉴스코스피, 미-이란 협상 기대감에 장중 6,000선 재돌파연합뉴스6시간 전네이버뉴스코스피, 미-이란 협상 기대감에 장중 6,000선 재돌파KBS6시간 전네이버뉴스뉴스17시간 전네이버뉴스Keep에 저장Keep에 바로가기트럼프 명령한 이란 항구 봉쇄·기뢰 제거…"최고 난이도 임무"도널드 트럼프 미국 대통령이 미 해군에 내린 이란 항구 봉쇄와 기뢰 제거 작전은 이란 전쟁 발발 이후 가장 어려운 임무가 될 것이라고 미국 CNN 방송이 13일(현지시간) 분석했다. 앞서 파키스탄 이슬라마바드에서 열린 미국과 이란의 종전 협상이 결렬되자 트럼프 대통령은 미 동부 시간 기준 13일 오전 10시... 호르무즈 막아선 美군함 15척…동맹 없인 이란 기뢰 못 뚫는다중앙일보3시간 전네이버뉴스일촉즉발 호르무즈…미, 군함 10여척 ‘역봉쇄’ vs 이란 “상상 못할 반...한겨레5시간 전네이버뉴스美, 호르무즈 이란 봉쇄·기뢰 제거 나섰지만…고난도 작전 전망연합뉴스10시간 전네이버뉴스미군, 기뢰 제거작업 착수… 이란도 정확한 위치 몰라 난관문화일보5시간 전네이버뉴스파이낸셜뉴스9시간 전네이버뉴스Keep에 저장Keep에 바로가기이란 대통령 "국제법 틀에서 협상, 성공 여부 美에 달려"이란의 마수드 페제시키안 대통령이 미국과 종전 협상과 관련해 오직 국제법에 따라 협상한다고 강조했다. 그는 앞서 합의 결렬이 미국 때문이라고 주장했다. 13일(현지시간) 이란 국영 IRNA 통신에 따르면 페제시키안은 이날 에마뉘엘 마크롱 프랑스 대통령과 전화 회담에서 "이란은 오직 국제법의 틀 안에서만... 이란 대통령 "국제법 테두리 내에서만 美와 대화"연합뉴스12시간 전네이버뉴스이데일리9시간 전네이버뉴스Keep에 저장Keep에 바로가기미·이란 “대화 계속”…봉쇄 속에도 협상 불씨 살아있다미국이 13일(현지시간) 이란에 대한 해상 봉쇄를 개시하며 중동 긴장이 다시 고조되고 있다. 그러나 군사적 압박 수위를 끌어올리는 와중에도 미국과 이란은 협상 채널을 완전히 닫지 않은 채 대화의 끈을 이어가는 모습이다. 공개적 대치는 격화하고 있지만, 물밑에서는 추가 협상 가능성을 열어둔 채 접촉이...




뉴스 기사와 댓글로 인한 문제 발생시 24시간 센터로 접수해주세요.






죄송합니다. 일시적인 오류입니다.
잠시 후 다시 시도해주십시오.
재시도


















네이버 검색은 최상의 검색 결과 품질을 위해 뉴스 검색결과를 2,000건까지 제공합니다.
        원하시는 검색 결과를 찾으시려면 더 구체적인 검색어를 입력해 보세요.

    연관 검색어 도움말   신고검색어제안 기능 닫기       미국이란전쟁     미국이란     이란 전쟁     이란 미국 협상     이란지도     이란 협상     이란 속보     이란 이스라엘     미국 이란 휴전     미국 이란 전쟁 속보     더보기  1주일간 닫힘 상태가 유지됩니다. 다시 보시겠습니까?열기           오늘은 어떤 취향을 남겨볼까요? 오늘 클립 챌린지      홈리빙 인기 스토어 확인 스토어의 발견      네이버에서 컬리를 멤버십 2만원 이상 무료배송      네이버가 더 편해지는 순간 웨일 브라우저 알아보기              이전                      정보를 가져오는 중입니다.       죄송합니다. 일시적인 오류입니다. 잠시 후 다시 시도해주십시오. 재시도           맨위로    이용약관 개인정보처리방침 검색 고객센터 © NAVER Corp.      맨위로    전체서비스 이용약관 개인정보처리방침 검색 고객센터 © NAVER Corp.

In [189]:
# 여러 클래스 중 가장 특징적인 것 하나만 사용해보기
target_class = "span.sds-comps-text-type-headline1"

In [199]:
# 4. 데이터 추출
for span in title_spans:
    # [+] 기사 제목 추출
    title = span.text.strip
    
    # [+] 기사 링크 추출: 제목(span)을 클릭 가능하게 만드는 부모 <a> 태그를 역추적하여 찾음
    parent_a_tag = span.find_parent('a')
    link = parent_a_tag['href'] if parent_a_tag and parent_a_tag.has_attr('href') else "링크 없음"
    
    extracted_data.append({
        '제목': title,
        '링크': link
    })

df = pd.DataFrame(extracted_data)
print(f"\n총 {len(df)}개의 기사를 추출했습니다.\n")
display(df)

총 20개의 기사를 추출했습니다.

,제목,링크
0,[단독] 이란에 26척 정보 넘긴 韓구출작전…‘역봉쇄’ 변수 만났다,https://www.joongang.co.kr/article/25419917
1,"미·이란, 물밑 대화 진행중…2차 대면협상 가능성도 준비",https://www.yna.co.kr/view/AKR2026041402030000...
2,"""미국-이란 협상단, 이번주 후반 파키스탄서 만난다""",https://news.tvchosun.com/site/data/html_dir/2...
3,"미, 해상봉쇄 시작…트럼프 “이란, 간절히 합의 원해”",https://news.kbs.co.kr/news/pc/view/view.do?nc...
4,"정부, 이란에 한국 선박 정보 공유‥통항 협의 주목",https://imnews.imbc.com/news/2026/politics/art...
5,"밴스 미 부통령 ""1차 협상단은 권한 없었다⋯이제 공은 이란에""",http://mbn.mk.co.kr/pages/news/newsView.php?ca...
6,"[속보] 미-이란 협상 기대감에 코스피, 장중 6000선 재돌파",https://www.kmib.co.kr/article/view.asp?arcid=...
7,"트럼프 명령한 이란 항구 봉쇄·기뢰 제거…""최고 난이도 임무""",https://www.news1.kr/world/usa-canada/6135351
8,"이란 대통령 ""국제법 틀에서 협상, 성공 여부 美에 달려""",http://www.fnnews.com/news/202604140743268153
9,미·이란 “대화 계속”…봉쇄 속에도 협상 불씨 살아있다,http://www.edaily.co.kr/news/newspath.asp?news...
10,<built-in method strip of str object at 0x0000...,https://www.joongang.co.kr/article/25419917
11,<built-in method strip of str object at 0x0000...,https://www.yna.co.kr/view/AKR2026041402030000...
12,<built-in method strip of str object at 0x0000...,https://news.tvchosun.com/site/data/html_dir/2...
13,<built-in method strip of str object at 0x0000...,https://news.kbs.co.kr/news/pc/view/view.do?nc...
14,<built-in method strip of str object at 0x0000...,https://imnews.imbc.com/news/2026/politics/art...
15,<built-in method strip of str object at 0x0000...,http://mbn.mk.co.kr/pages/news/newsView.php?ca...
16,<built-in method strip of str object at 0x0000...,https://www.kmib.co.kr/article/view.asp?arcid=...
17,<built-in method strip of str object at 0x0000...,https://www.news1.kr/world/usa-canada/6135351
18,<built-in method strip of str object at 0x0000...,http://www.fnnews.com/news/202604140743268153
19,<built-in method strip of str object at 0x0000...,http://www.edaily.co.kr/news/newspath.asp?news...

In [201]:
extracted_data

[{'제목': '[단독] 이란에 26척 정보 넘긴 韓구출작전…‘역봉쇄’ 변수 만났다',
  '링크': 'https://www.joongang.co.kr/article/25419917'},
 {'제목': '미·이란, 물밑 대화 진행중…2차 대면협상 가능성도 준비',
  '링크': 'https://www.yna.co.kr/view/AKR20260414020300009?input=1195m'},
 {'제목': '"미국-이란 협상단, 이번주 후반 파키스탄서 만난다"',
  '링크': 'https://news.tvchosun.com/site/data/html_dir/2026/04/14/2026041490250.html'},
 {'제목': '미, 해상봉쇄 시작…트럼프 “이란, 간절히 합의 원해”',
  '링크': 'https://news.kbs.co.kr/news/pc/view/view.do?ncd=8534878&ref=A'},
 {'제목': '정부, 이란에 한국 선박 정보 공유‥통항 협의 주목',
  '링크': 'https://imnews.imbc.com/news/2026/politics/article/6815019_36911.html'},
 {'제목': '밴스 미 부통령 "1차 협상단은 권한 없었다⋯이제 공은 이란에"',
  '링크': 'http://mbn.mk.co.kr/pages/news/newsView.php?category=mbn00008&news_seq_no=5187962'},
 {'제목': '[속보] 미-이란 협상 기대감에 코스피, 장중 6000선 재돌파',
  '링크': 'https://www.kmib.co.kr/article/view.asp?arcid=0029676336&code=61141111&cp=nv'},
 {'제목': '트럼프 명령한 이란 항구 봉쇄·기뢰 제거…"최고 난이도 임무"',
  '링크': 'https://www.news1.kr/world/usa-canada/6135351'},
 {'제목': '이란 대통령 "국제법 틀에서 협상, 성공 여부 美에 달려"',
  '링크': 'http://www.fnnews.com/news/202604140743268153'},
 {'제목': '미·이란 “대화 계속”…봉쇄 속에도 협상 불씨 살아있다',
  '링크': 'http://www.edaily.co.kr/news/newspath.asp?newsid=02440326645416120'},
 {'제목': <function str.strip(chars=None, /)>,
  '링크': 'https://www.joongang.co.kr/article/25419917'},
 {'제목': <function str.strip(chars=None, /)>,
  '링크': 'https://www.yna.co.kr/view/AKR20260414020300009?input=1195m'},
 {'제목': <function str.strip(chars=None, /)>,
  '링크': 'https://news.tvchosun.com/site/data/html_dir/2026/04/14/2026041490250.html'},
 {'제목': <function str.strip(chars=None, /)>,
  '링크': 'https://news.kbs.co.kr/news/pc/view/view.do?ncd=8534878&ref=A'},
 {'제목': <function str.strip(chars=None, /)>,
  '링크': 'https://imnews.imbc.com/news/2026/politics/article/6815019_36911.html'},
 {'제목': <function str.strip(chars=None, /)>,
  '링크': 'http://mbn.mk.co.kr/pages/news/newsView.php?category=mbn00008&news_seq_no=5187962'},
 {'제목': <function str.strip(chars=None, /)>,
  '링크': 'https://www.kmib.co.kr/article/view.asp?arcid=0029676336&code=61141111&cp=nv'},
 {'제목': <function str.strip(chars=None, /)>,
  '링크': 'https://www.news1.kr/world/usa-canada/6135351'},
 {'제목': <function str.strip(chars=None, /)>,
  '링크': 'http://www.fnnews.com/news/202604140743268153'},
 {'제목': <function str.strip(chars=None, /)>,
  '링크': 'http://www.edaily.co.kr/news/newspath.asp?newsid=02440326645416120'}]

In [197]:
import pandas as pd

# 1. 클래스명을 짧게 줄여서 다시 타겟팅해보기 (이전 단계에서 수정한 부분)
target_class = "span.sds-comps-text-type-headline1"
title_spans = soup.select(target_class) 

# [+] 태그를 제대로 찾았는지 먼저 확인!
print(f"찾아낸 태그 개수: {len(title_spans)}개")

# 2. 데이터 추출
extracted_data = []

for span in title_spans:
    # [+] 기사 제목 추출 (오타 수정: strip() 괄호 추가)
    title = span.text.strip()
    
    # [+] 기사 링크 추출
    parent_a_tag = span.find_parent('a')
    link = parent_a_tag['href'] if parent_a_tag and parent_a_tag.has_attr('href') else "링크 없음"
    
    extracted_data.append({
        '제목': title,
        '링크': link
    })

# 3. DataFrame으로 변환 및 확인
df = pd.DataFrame(extracted_data)
print(f"\n총 {len(df)}개의 기사를 추출했습니다.\n")
display(df)

찾아낸 태그 개수: 10개

총 10개의 기사를 추출했습니다.

,제목,링크
0,[단독] 이란에 26척 정보 넘긴 韓구출작전…‘역봉쇄’ 변수 만났다,https://www.joongang.co.kr/article/25419917
1,"미·이란, 물밑 대화 진행중…2차 대면협상 가능성도 준비",https://www.yna.co.kr/view/AKR2026041402030000...
2,"""미국-이란 협상단, 이번주 후반 파키스탄서 만난다""",https://news.tvchosun.com/site/data/html_dir/2...
3,"미, 해상봉쇄 시작…트럼프 “이란, 간절히 합의 원해”",https://news.kbs.co.kr/news/pc/view/view.do?nc...
4,"정부, 이란에 한국 선박 정보 공유‥통항 협의 주목",https://imnews.imbc.com/news/2026/politics/art...
5,"밴스 미 부통령 ""1차 협상단은 권한 없었다⋯이제 공은 이란에""",http://mbn.mk.co.kr/pages/news/newsView.php?ca...
6,"[속보] 미-이란 협상 기대감에 코스피, 장중 6000선 재돌파",https://www.kmib.co.kr/article/view.asp?arcid=...
7,"트럼프 명령한 이란 항구 봉쇄·기뢰 제거…""최고 난이도 임무""",https://www.news1.kr/world/usa-canada/6135351
8,"이란 대통령 ""국제법 틀에서 협상, 성공 여부 美에 달려""",http://www.fnnews.com/news/202604140743268153
9,미·이란 “대화 계속”…봉쇄 속에도 협상 불씨 살아있다,http://www.edaily.co.kr/news/newspath.asp?news...